package kr.spring.admin.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import kr.spring.admin.vo.AdminVO;
import kr.spring.admin.vo.EventVO;
import kr.spring.admin.vo.FaqVO;
import kr.spring.admin.vo.NoticeVO;
import kr.spring.admin.vo.RefundMbVO;
import kr.spring.admin.vo.ReplyVO;
import kr.spring.assignment.vo.AssignVO;
import kr.spring.board.vo.BoardVO;
import kr.spring.cinema.vo.CinemaVO;
import kr.spring.cinema.vo.TheaterVO;
import kr.spring.member.vo.PointVO;
import kr.spring.movie.vo.MovieVO;
import kr.spring.shop.vo.OrdersVO;
import kr.spring.support.vo.ConsultVO;

public interface AdminService {
	public List<AdminVO> selectMemberList(Map<String,Object> map);
	public Integer selectMemberRowCount(Map<String,Object> map);
	public Integer totalMember();
	public void updateMemberAuth(long mem_num);
	public void deleteMemberAuth(long mem_num);
	public List<AdminVO> selectMembershipList(Map<String,Object> map);
	public Integer selectMembershipRowCount(Map<String,Object> map);
	public List<EventVO> selectEventList(Map<String,Object> map);
	public Integer selectEventRowCount(Map<String,Object> map);
	public void insertEvent(EventVO eventVO);
	public EventVO selectEvent(long event_num);
	public void modifyEvent(EventVO eventVO);
	public void deleteEvent(long event_num);
	public List<NoticeVO> selectNoticeList(Map<String,Object> map);
	public Integer selectNoticeRowCount(Map<String,Object> map);
	public void insertNotice(NoticeVO noticeVO);
	public NoticeVO selectNotice(long nb_num);	
	public void modifyNotice(NoticeVO noticeVO);
	public void deleteNotice(long nb_num);
 	public List<FaqVO> selectFaqList(Map<String,Object> map);
 	public Integer selectFaqRowCount(Map<String,Object> map);
    public void insertFaq(FaqVO FaqVO);
    public void deleteFaq(long f_num);
	public List<BoardVO> selectCommunityList(Map<String,Object> map);
	public Integer selectCommunityRowCount(Map<String,Object> map);
	public List<AssignVO> selectAssginList(Map<String,Object> map);
	public Integer selectAssignRowCount(Map<String,Object> map);
	public List<ReplyVO> selectReplyList(Map<String,Object> map);
	public List<ReplyVO> selectReCmtList(Map<String,Object> map);
	public Integer selectReplyRowCount(Map<String,Object> map);
	public Integer selectReCmtRowCount(Map<String,Object> map);
	public void deleteReply(long cc_num);
	public void deleteCmt(long cc_num);	
	public List<MovieVO> selectMovie(Map<String,Object> map);
	public Integer selectMovieRowCount(Map<String,Object> map);
	public List<PointVO> selectPoint(Map<String,Object> map);
	public Integer selectPointRowCount(Map<String,Object> map);
	public Integer deleteMovie(long m_code);
	public Integer totalCommunity();
	public Integer totalAssignment();
	public Integer totalProduct();
	public Integer totalMovie();
	public Integer totalCinema();
	public Integer totalConsult();
	public void insertCinema(CinemaVO cinemaVO);
	public List<TheaterVO> selectTheater(int c_num);
	public List<CinemaVO> selectCinema(Map<String,Object> map);
	public Integer selectCinemaRowCount(Map<String,Object> map);
	public void deleteCinema(long c_num);
	public void refundPoint(long ph_num, long mem_num, long ph_point, String ph_payment);
	public void refundMembership(long mem_num, String point_payment);
	public List<ConsultVO> selectConsultList(Map<String,Object>map);
	public Integer selectConsultRowCount(Map<String,Object> map);
	public ConsultVO selectConsult(long consult_num);
	public void updateAnswer(ConsultVO consultVO);
	public List<RefundMbVO> selectReservation(Map<String,Object> map);
	public Integer selectReservationRowCount(Map<String,Object> map);
	public Integer totalMb(@Param("mb_num") long mb_num);
	public void refundMovie(@Param("mem_num") long mem_num, @Param("mb_price") long mb_price, @Param("ph_payment") String ph_payment,@Param("mb_num") long mb_num);
	public List<OrdersVO> selectOrder(Map<String, Object> map);
	public Integer selectOrderRowCount(Map<String, Object> map);	
	public void refundShop(@Param("mem_num") long mem_num,@Param("ph_payment") String ph_payment,@Param("order_num") long order_num,@Param("order_quantity") long order_quantity,@Param("p_price") long p_price);
	public MovieVO selectMovie1(long m_code);
	public void modifyMovie(MovieVO movieVO);
	public Integer selectEventParticipantsCnt(long event_num);
	public List<EventVO> selectEventParticipants(long event_num);
	public int selectChoiceNumber(long event_num);
	public List<Long> selectMemberNumberEvent(long event_num);
	public void updateEventResult(long mem_num,long event_num);
	public Integer selectEventResultShow(long event_num);


}	
